### PR TITLE
Autoresizing

### PR DESCRIPTION
**Pull request by schriftgestalt**

### CODE REVIEW

**Comment by frankrolf** [comment]
Thank you, this looks useful.
Two questions:
 – are the .pyc files needed?
– could it be done with less code duplication?

**Comment by schriftgestalt** [comment]
The foo commit was not supposed to show up here. I make a new pull request.

**Comment by miguelsousa** [comment]
Looks like Georg made a Glyphs feature out of the extension. Nice.

**Comment by schriftgestalt** [comment]
I really like the extension. Thanks for it. And It is always a good test for my roboFab/fontParts implantation to port an plugin like this (I found a few issues, so the plugin will not work in the current version of Glyphs. 
And have a look here: #4

**Pull request closed without merging**
